version: '3.8'
services:
  quarkus-backend:
    image: vzupa/quarkus-be
    ports:
      - "8080:8080"
    networks:
      - my-network

  react-frontend:
    image: vzupa/react-fe
    ports:
      - "3000:80"
    networks:
      - my-network

networks:
  my-network:
