name: Quarkus CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Grant execute permission for mvnw
      run: chmod +x mvnw
      working-directory: ./quarkus_be

    - name: Build Backend with Maven
      run: ./mvnw package
      working-directory: ./quarkus_be

  sonarcloud-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for mvnw
      run: chmod +x mvnw
      working-directory: ./quarkus_be

    - name: Analyze with SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Vzupa_zimskaSola24 -Dsonar.qualitygate.wait=false
      working-directory: ./quarkus_be
      
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Grant execute permission for mvnw
      run: chmod +x mvnw
      working-directory: ./quarkus_be

    - name: Build and Push Backend Docker Image
      run: |
        cd ./quarkus_be
        ./mvnw package
        docker build -f src/main/docker/Dockerfile.jvm -t vzupa/quarkus-be .
        docker push vzupa/quarkus-be

    - name: Build and Push Frontend Docker Image
      run: |
        cd ./zimska24
        docker build -t vzupa/react-fe .
        docker push vzupa/react-fe
