name: Quarkus CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Grant execute permission for mvnw
      run: chmod +x mvnw
      working-directory: ./quarkus_be
      
    - name: Build with Maven and Analyze with SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Vzupa_zimskaSola24 -Dsonar.qualitygate.wait=false
      working-directory: ./quarkus_be

    - name: Upload resulting Build package
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: quarkus_be/target/

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Package Backend Application
      run: ./mvnw package
      working-directory: ./quarkus_be

    - name: Build Backend Docker Image
      run: docker build -f src/main/docker/Dockerfile.jvm -t vzupa/quarkus-be .
      working-directory: ./quarkus_be

    - name: Push Backend Docker Image
      run: docker push vzupa/quarkus-be
      working-directory: ./quarkus_be

    - name: Build Frontend Docker Image
      run: docker build -t vzupa/react-fe .
      working-directory: ./ZimskaSola24

    - name: Push Frontend Docker Image
      run: docker push vzupa/react-fe
      working-directory: ./ZimskaSola24
